trayio/falafel

- package.json
Updating needle dependancy and version bump
> Updating needle dependancy and version bump

- package.json
> Updated threadneedle

- lib/fileHandler/index.js
- package.json
Download a file to disk rather than create an in memory buffer
> Download File To Disk

- lib/buildConnectorsJson/index.js
Needed for Dynamic Output Schemas
> Added dynamic_output as a new configuration option for messages

- exampleArtisanTwo/config.json
- lib/parseConfig/getModel.js
- lib/parseConfig/index.js
- package.json
Explicitly defined headers in config take priority
> Operation level options is now processed

- .gitignore
- package-lock.json
package.lock should usually be commited
> commit package lock

- lib/bindConnectors/index.js
- package.json
- test/bindConnectors/index.js
- test/falafel.js
Added logic that would explicitly end the promise if a timeout value can be retrieved from `context.getRemainingTimeInMillis()`.
> CN 40/promise timeout

- lib/utils/getDirectories.js
- lib/utils/getFiles.js
- package.json
Adding try/catch to file handling code (`getDirectories` and `getFiles`).
> CN 44/f/catch directory loading errors

- lib/fileHandler/index.js
- package-lock.json
- package.json
`partSize` and `queueSize` now have defaults, scaling to half the RAM usage
> CPS-125: partSize and queueSize specified for s3 upload

- README.md
- lib/bindConnectors/bindTriggerRequest.js
- lib/bindConnectors/parseRequestBody.js
- package-lock.json
- package.json
- test/bindConnectors/bindTriggerRequest.js
- test/falafel.js
Fixed response format (resolved and rejected) for when request is a function instead of an object.
Added tests to check format.
> CPS-145: request function response format

- lib/parseConfig/handleOAuthRefresh.js
- package-lock.json
- package.json
- test/parseConfig/handleOAuthRefresh.js
`#oauth_refresh` is now set as the code for refreshing
> CPS-161: artisan refresh hash code

- exampleRawHttpRequest/connectors.json
- exampleRawHttpRequest/docs.html
- lib/rawHttpRequest/formatOutput.js
- lib/rawHttpRequest/rawHttpRequestSchema.js
- package-lock.json
- package.json
- rawHttpRequest.md
- Schema has been updated
- Size check has been added in afterSuccess
- Docs updated to indicate need for connector doc to mention base URL and authentication method
A beta release of this will be published after approval
> CPS-182: raw http request updates

- .eslintrc.js
- exampleRawHttpRequest/connectors.json
- lib/bindUtils/index.js
- lib/buildConnectorsJson/generateSchemaFromJs.js
- lib/rawHttpRequest/convertArrayFormatToObject.js
- lib/rawHttpRequest/getContentTypeFromBody.js
- lib/rawHttpRequest/processOptions.js
- lib/rawHttpRequest/rawHttpRequestModel.js
- lib/rawHttpRequest/rawHttpRequestSchema.js
- lib/rawHttpRequest/validateAndProcessBody.js
- lib/rawHttpRequest/validateBody.js
- package-lock.json
- package.json
- rawHttpRequest.md
- test/rawHttpRequest/processOptions_test.js
- test/rawHttpRequest/validateBody_test.js
- #139 CPS-184: Raw HTTP Request body validation
- #140  CPS-183: Raw  HTTP Request options processing
- Includes response parsing flag
> CPS-185: Falafel v1.25.1

- lib/rawHttpRequest/processOptions.js
- package-lock.json
- package.json
- test/rawHttpRequest/processOptions_test.js
- multipart flag was erring if contentType was undefined - this is now fixed.
- json flag was incorrect when bodyType is none - also fixed.
- test added.
> CPS-186: v1.25.2 - rawHttpRquest multipart bug fix

- lib/rawHttpRequest/index.js
- package-lock.json
- package.json
Bug fix due to typo when creating sanitised model config
> CPS-191: rawHttpRequest globals flag bug

- lib/buildConnectorsJson/prettyTitle.js
- lib/fileHandler/index.js
- package-lock.json
- package.json
- test/buildConnectorsJson/index.js
- test/buildConnectorsJson/prettyTitle.js
#145 CPS-193: File handling with max RAM environment variable
#144 CPS-142: JSON Schema titles capitalise ID and URL
> CPS-194: Falafel v1.26.0 release

- exampleRawHttpRequest/connectors.json
- exampleRawHttpRequest/connectors/testconnector/rawHttpRequest.js
- exampleRawHttpRequest/docs.html
- lib/rawHttpRequest/index.js
- lib/rawHttpRequest/rawHttpRequestSchema.js
- CPS-201: operation title update
- CPS-207: configuration option for restricting URL options
- CPS-198: required properties in schema updated
- Also added more descriptions
> CPS-209: Raw HTTP request updates

- lib/fileHandler/index.js
- test/fileHandler/index_test.js
Fixes [Link to Jira Ticket](https://trayio.atlassian.net/browse/CPS-215)
- Added validation check to `download` and `streamDownload` functions
- added accompanying tests
> [CPS-215] falafel add validation to falafel to make sure that a given tray file has the standard props

- lib/bindConnectors/formatError.js
- lib/parseConfig/getFunctionParameter.js
- lib/parseConfig/getGlobalModel.js
- lib/parseConfig/getHelper.js
- lib/parseConfig/getModel.js
- lib/parseConfig/normalizeModelParameter.js
- package-lock.json
- package.json
- test/parseConfig/getFunctionParameter.js
- test/parseConfig/getGlobalModel.js
- test/parseConfig/getHelper.js
- test/parseConfig/getModel.js
- test/parseConfig/normalizeModelParameter.js
Some attempted improvement in the artisan error handling for connector debugging purposes
(Note: I'm avoiding modifying too much, given artisan v1 is being deprecated)
> CPB-266: artisan error handling update

- lib/fileHandler/index.js
- package-lock.json
- package.json
- test/fileHandler/index_test.js
* Upgraded threadneedle to latest so that it uses forked needle
* Switched to forked needle in this package to avoid double import
* Fixed npm audit
* Bumped version
> [CSP-6876] bump threadneedle, switch to @trayio/needle, version bump

- package-lock.json
- package.json
bump versions for falafel and thredaneedle
> [CSP-7247] bump vesrions for falafel and thredaneedle

- .npmignore
- docs/pages/file_handling.md
- docs/pages/getting_started.md
- docs/pages/index.md
- docs/pages/raw_http_request.md
- docs/pages/trigger_connectors.md
- docs/pages/utils.md
Added a simple getting started guide that walks a user through the process of setting up a connector from scratch and calling the included sample operation
> [CSP-7538] getting started guide

- docs/pages/index.md
- docs/pages/input_schema/common_properties.md
- docs/pages/input_schema/index.md
- docs/pages/input_schema/input_types.md
- docs/pages/utils.md
Added documentation for writing input schemas. 
Haven't covered DDLs and `lookup` as those will be covered as a broader topic in a later ticket
> [CSP-7539] input schema docs

- docs/pages/input_schema/common_properties.md
- docs/pages/input_schema/input_types.md
- docs/pages/input_schema/oneof.md
Ported over oneOf input docs from notion, with some wording tweaks
> [CSP-7568] Add oneOf docs

- docs/pages/ddl.md
- docs/pages/input_schema/common_properties.md
- docs/pages/input_schema/index.md
> [CSP-7569] DDL Docs

- package-lock.json
- package.json
Patch bump
- Threadneedle patch bump
- npm audit fixes
> CN-649: threadneedle patch

- .eslintrc.js
- lib/bindConnectors/bindMessage.js
- lib/bindConnectors/bindMessageHooks.js
- lib/bindConnectors/formatInputBody/date.js
- lib/bindConnectors/parseRequestBody.js
- lib/buildConnectorsJson/prettyTitle.js
- lib/fileHandler/index.js
- lib/index.js
- lib/parseConfig/handleOAuthRefresh.js
- lib/parseConfig/index.js
- lib/utils/isUnixSecondTimestamp.js
- lib/utils/mout.js
- package-lock.json
- package.json
- test/fileHandler/index_test.js
- test/utils/mout_test.js
Removed `mout` dependency by cloning the methods used in falafel and their tests.
> CN-849: mout vulnerability

- package-lock.json
- package.json
- threadneedle bumped to v1.16.0
- minor bump
> CN-1419: threadneedle bump

- lib/bindConnectors/index.js
- lib/index.js
- lib/monitoring/bindMonitoring.js
- package-lock.json
- package.json
This reverts commit 13fd60588c0d4410fd350d0999c3d2615c27ce5a.
> Revert "[CN-1563] test beta v1 falafel on staging (#205)"

- package-lock.json
- package.json
update `aws-sdk` to version `^2.1354.0` to resolve transient dependency issue in `xml2js`
Dependency route: falafel -> aws-sdk -> xml2js
> [CE-1662] update aws-sdk version

- package-lock.json
- package.json
- updated @trayio/needle dep to use latest version
- updated threadneedle dep
- minor bump
> CN-1712: needle xm2ljs update

- package-lock.json
- package.json
> CN-2486: threadneedle bump (soap dep vulnerability)
